// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace WebAPIHomeTask2.Models
{
    public partial class CoronaVaccine
    {
        public CoronaVaccine()
        {
            VaccineToEmployees = new HashSet<VaccineToEmployee>();
        }

        public int CoronaVaccineId { get; set; }
        public string Manufacturer { get; set; }
        public int NumberOfVaccine { get; set; }

        public virtual ICollection<VaccineToEmployee> VaccineToEmployees { get; set; }
    }
}