// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace WebAPIHomeTask2.Models
{
    public partial class Employee
    {
        public Employee()
        {
            VaccineToEmployees = new HashSet<VaccineToEmployee>();
        }

        public string EmployeeId { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public DateTime DateOfBirth { get; set; }
        public string Telephone { get; set; }
        public string MobilePhone { get; set; }
        public string City { get; set; }
        public string Street { get; set; }
        public string Number { get; set; }
        public DateTime? PositiveResultDate { get; set; }
        public DateTime? RecoveryDate { get; set; }

        public virtual ICollection<VaccineToEmployee> VaccineToEmployees { get; set; }
    }
}